### ISSUE TITLE
Dockerfile does not pull updated homeassistant image

### ISSUE THREAD

**Issue by kunago** [vladbabii/homeassistant-socat#6]
Unless I am doing something bad on my side, whenever I run
```
docker-compose pull
```
then the image does not get updated even though homeassistant is already of a higher version. I can get around this by running
```
docker-compose down
docker image prune -a
docker-compose pull
```
but it does not seem to be the most elegant way to achieve the result.

Can you help me out here what needs to be changed in the Dockerfile so the newest homeassistant version is downloaded once it is available?

**Comment by kunago** [comment]
Okay, my bad - I am simply stuck with homeassistant version 0.99.3 no matter what I do, yet there already exsists version 0.106.2. Any hints?

**Comment by vladbabii** [comment]
Rebuilding a newer image now. Should be available on docker hub in a couple of minutes
